### PR TITLE
Fix small bug fix with onReady Event and Refactoring in demo index.zul

### PR DESCRIPTION
**Pull request by nice-redbull**
Fix small bug fix with onReady Event and Refactoring in demo index.zul

### CODE REVIEW

**Comment by connollyst** [comment]
That's great, thanks Konstantin.
I plan to add more features and charts as we go, feel free to suggest/contribute anything you find lacking.

**Comment by connollyst** [comment]
PS: I'll release these changes to Maven central soon

**Comment by connollyst** [comment]
[Released](https://github.com/connollyst/zkgooglecharts/releases/tag/zkgooglecharts-0.2.2) and [deployed](http://search.maven.org/#artifactdetails%7Corg.zkoss%7Czkgooglecharts%7C0.2.2%7Cjar).

Thanks again.

**Comment by nice-redbull** [comment]
ok.  thanks.

**Pull request merged**
